# TODO specify exact versions on which it has to work
language: cpp
script: make test
os:
  - linux
  #- osx
dist: trusty
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libboost-all-dev
      - libhdf5-serial-dev
      
# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?
compiler:
  - clang
    addons:
      apt:
        packages:
          - clang-3.8
    env: COMPILER=clang++-3.8
  - gcc
    addons:
      apt:
        packages:
          - gcc-5
          - g++-5
    env: COMPILER=g++-5

env:
  - OMP_NUM_THREADS=4
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/hdf5; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 60 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-3.8; fi

notifications:
  slack: 
    rooms:
      - apollo-stride:u6J7UHJdtlvVNtnUjyRndtgh#general
    on_failure: always
    on_success: change
  email: false
