# Some advice on this configuration was taken from:
# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?

# TODO specify exact versions on which it has to work

# Generic language, because we prefer to handle C++ configuration ourselves
language: generic

dist: trusty

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &deps
      - libboost-all-dev
      - libhdf5-serial-dev

gcc_addons: &gcc_addons
    apt:
        sources:
            - *sources
        packages:
            - *deps
            - gcc-5
            - g++-5

clang_addons: &clang_addons
    apt:
        sources:
            - *sources
        packages:
            - *deps
            - clang-3.8
        

matrix:
  include:
  
    # Unit tests ......................
    
    - addons: *gcc_addons
      env: 
        - test='unit'
        - unipar=dummy
        - compiler=gcc
      
    - addons: *clang_addons
      env: 
        - test='unit'
        - unipar=dummy
        - compiler=clang
    
    #- addons: *gcc_addons
      #env: 
        #- test='unit'
        #- unipar=TBB
        #- compiler=gcc
      
    #- addons: *clang_addons
      #env: 
        #- test='unit'
        #- unipar=TBB
        #- compiler=clang
    
    #- addons: *gcc_addons
      #env: 
        #- test='unit'
        #- unipar=OpenMP
        #- compiler=gcc
      
    #- addons: *clang_addons
      #env: 
        #- test='unit'
        #- unipar=OpenMP
        #- compiler=clang
    
    ## Scenario tests ..................
    
    #- addons: *gcc_addons
      #env: 
        #- test=scenarios
        #- unipar=dummy
        #- compiler=gcc
      
    #- addons: *clang_addons
      #env: 
        #- test=scenarios
        #- unipar=dummy
        #- compiler=clang
    
    #- addons: *gcc_addons
      #env: 
        #- test=scenarios
        #- unipar=TBB
        #- compiler=gcc
      
    #- addons: *clang_addons
      #env: 
        #- test=scenarios
        #- unipar=TBB
        #- compiler=clang
    
    - addons: *gcc_addons
      env: 
        - test=scenarios
        - unipar=OpenMP
        - compiler=gcc
      
    - addons: *clang_addons
      env: 
        - test=scenarios
        - unipar=OpenMP
        - compiler=clang


before_install:
  - . ./travis/before_install.sh  # thanks https://github.com/travis-ci/travis-ci/issues/1313
  - PARALLEL_MAKE=2 make install

script:
  - ./travis/script.sh

notifications:
  slack: 
    rooms:
      - apollo-stride:u6J7UHJdtlvVNtnUjyRndtgh#repo
    on_failure: always
    on_success: change
  email: false
